# Generated by Django 3.1.7 on 2021-03-28 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('ingredients', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(default='main.jpg', upload_to='')),
                ('quantity', models.IntegerField(default=0)),
                ('is_vegan', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.restaurantprofile')),
            ],
        ),
    ]
