# Generated by Django 3.1.7 on 2021-04-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_donationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servings',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
