# Generated by Django 3.1.7 on 2021-04-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210414_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='request_type',
            field=models.CharField(choices=[('Donation', 'Donation'), ('Request', 'Request')], default='Donation', max_length=25),
        ),
    ]
