export const RESTAURANT_LIST_REQUEST = 'RESTAURANT_LIST_REQUEST' 
export const RESTAURANT_LIST_SUCCESS = 'RESTAURANT_LIST_SUCCESS' 
export const RESTAURANT_LIST_FAIL = 'RESTAURANT_LIST_FAIL' 

export const RESTAURANT_SERVINGS_REQUEST = 'RESTAURANT_SERVINGS_REQUEST' 
export const RESTAURANT_SERVINGS_SUCCESS = 'RESTAURANT_SERVINGS_SUCCESS' 
export const RESTAURANT_SERVINGS_FAIL = 'RESTAURANT_SERVINGS_FAIL'

export const RESTAURANT_SERVINGS_DETAILS_REQUEST = 'RESTAURANT_SERVINGS_DETAILS_REQUEST' 
export const RESTAURANT_SERVINGS_DETAILS_SUCCESS = 'RESTAURANT_SERVINGS_DETAILS_SUCCESS' 
export const RESTAURANT_SERVINGS_DETAILS_FAIL = 'RESTAURANT_SERVINGS_DETAILS_FAIL'

export const RESTAURANT_PROFILE_REQUEST = 'RESTAURANT_PROFILE_REQUEST' 
export const RESTAURANT_PROFILE_SUCCESS = 'RESTAURANT_PROFILE_SUCCESS' 
export const RESTAURANT_PROFILE_FAIL = 'RESTAURANT_PROFILE_FAIL'

export const RESTAURANT_DETAILS_REQUEST = 'RESTAURANT_DETAILS_REQUEST' 
export const RESTAURANT_DETAILS_SUCCESS = 'RESTAURANT_DETAILS_SUCCESS' 
export const RESTAURANT_DETAILS_FAIL = 'RESTAURANT_DETAILS_FAIL'


