export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'


export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'


export const USER_DONATE_REQUEST = 'USER_DONATE_REQUEST'
export const USER_DONATE_SUCCESS = 'USER_DONATE_SUCCESS'
export const USER_DONATE_FAIL = 'USER_DONATE_FAIL'

export const USER_DONATIONS_LIST_REQUEST = 'USER_DONATIONS_LIST_REQUEST'
export const USER_DONATIONS_LIST_SUCCESS = 'USER_DONATIONS_LIST_SUCCESS'
export const USER_DONATIONS_LIST_FAIL = 'USER_DONATIONS_LIST_FAIL'